# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Build, package, and deploy Python packages for microsoft_agents_m365copilot

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  paths:
    include:
      - 'python/packages/microsoft_agents_m365copilot/generated/**'
      - 'python/packages/microsoft_agents_m365copilot/src/agents_m365_copilot_request_adapter.py'      
      - 'python/packages/microsoft_agents_m365copilot/src/agents_m365_copilot_service_client.py'
  tags:
    include:
      - 'microsoft_agents_m365copilot_*'
    exclude:
      - 'microsoft_agents_m365copilot_beta*'

variables:
  library_name_v1: 'microsoft_agents_m365copilot'
  library_dir_v1: 'packages/microsoft_agents_m365copilot'

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      vmImage: ubuntu-latest
    stages:

    - stage: build
      displayName: 'Build and Package V1 Python'
      # This condition allows the build to run for both tagged builds and manual builds, but not for beta tagged commits.
      condition: |
        and
        (
          or
          (
            contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot'),
            eq(variables['Build.Reason'], 'Manual')
          ),
          not
          (
            contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot_beta')
          )
        )

      jobs:
        - job: build_python
          displayName: 'Build, Test, and Package V1'
          pool:
            name: Azure-Pipelines-1ESPT-ExDShared
            vmImage: ubuntu-latest

          steps:
            - task: UsePythonVersion@0
              displayName: 'Install Python 3.x'
              inputs:
                versionSpec: '3.x'
                addToPath: true

            - script: python -m pip install --upgrade pip

            # Build, test, and package V1 Python library
            - script: pip install poetry
              displayName: 'Install Poetry'
              workingDirectory: '$(Build.SourcesDirectory)/python/$(library_dir_v1)'
              # This condition allows the build to run for both tagged V1 builds or manual builds.
              condition: |
                and
                (
                  or
                  (
                    contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot'),
                    eq(variables['Build.Reason'], 'Manual')
                  ),
                  not
                  (
                    contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot_beta')
                  )
                )
            - script: poetry install
              displayName: 'Install v1 dependencies'
              workingDirectory: '$(Build.SourcesDirectory)/python/$(library_dir_v1)'
              condition: |
                and
                (
                  or
                  (
                    contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot'),
                    eq(variables['Build.Reason'], 'Manual')
                  ),
                  not
                  (
                    contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot_beta')
                  )
                )
            - script: poetry run isort .
              displayName: 'Check import order'
              workingDirectory: '$(Build.SourcesDirectory)/python/$(library_dir_v1)'
              condition: |
                and
                (
                  or
                  (
                    contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot'),
                    eq(variables['Build.Reason'], 'Manual')
                  ),
                  not
                  (
                    contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot_beta')
                  )
                )
            - script: poetry build
              displayName: 'Build Python package'
              condition:  |
                and
                (
                  or
                  (
                    contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot'),
                    eq(variables['Build.Reason'], 'Manual')
                  ),
                  not
                  (
                    contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot_beta')
                  )
                )
              workingDirectory: '$(Build.SourcesDirectory)/python/$(library_dir_v1)'
              
            - task: CopyFiles@2
              inputs:
                CleanTargetFolder: true
                sourceFolder: '$(Build.SourcesDirectory)/python/$(library_dir_v1)/dist/'
                targetFolder: '$(Build.ArtifactStagingDirectory)/python/$(library_name_v1)'
                Contents: |
                  *.tar.gz
                  *.whl
              displayName: "Copy V1 Python package files"
              condition:  |
                and
                (
                  or
                  (
                    contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot'),
                    eq(variables['Build.Reason'], 'Manual')
                  ),
                  not
                  (
                    contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot_beta')
                  )
                )
          templateContext:
            outputs:
              - output: pipelineArtifact
                displayName: 'Stage V1 Python package artifact'
                artifactName: pypi_$(library_name_v1)
                targetPath: '$(Build.ArtifactStagingDirectory)/python/$(library_name_v1)' 
                condition:  |
                  and
                  (
                    or
                    (
                      contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot'),
                      eq(variables['Build.Reason'], 'Manual')
                    ),
                    not
                    (
                      contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot_beta')
                    )
                  )
    - stage: deploy
      displayName: 'Publish Beta Python Package'
      dependsOn: build
      # This condition allows the build to run for only tagged builds. Manual runs are temp and should be removed after validation.
      condition: |
        or
        (
          and
          (
            contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot'),
            succeeded(),
            not
            (
              contains(variables['Build.SourceBranch'], 'microsoft_agents_m365copilot_beta')
            )
          ), 
          eq(variables['Build.Reason'], 'Manual')
        )             
      jobs:
        - deployment: publish_python_packages
          displayName: 'Publish V1 Python Package'
          environment: agents-m365copilot-prod          
          pool:
            name: Azure-Pipelines-1ESPT-ExDShared
            image: ubuntu-latest
            os: linux

          templateContext:
              type: releaseJob
              isProduction: true
              inputs:
                - input: pipelineArtifact
                  artifactName: pypi_$(library_name_v1)
                  targetPath: '$(Build.ArtifactStagingDirectory)/python'
          strategy:
            runOnce:
              deploy:
                steps:    
                - task: EsrpRelease@9
                  displayName: 'Publish V1 Python package via ESRP Release'
                  inputs:
                    connectedservicename: "Federated DevX ESRP Managed Identity Connection"
                    usemanagedidentity: false
                    keyvaultname: 'akv-prod-eastus'
                    authcertname: 'ReferenceLibraryPrivateCert'
                    signcertname: 'ReferencePackagePublisherCertificate'
                    clientid: '65035b7f-7357-4f29-bf25-c5ee5c3949f8'
                    intent: 'PackageDistribution'
                    contenttype: 'PYPI'
                    contentsource: 'Folder'
                    folderlocation: '$(Build.ArtifactStagingDirectory)/python'
                    waitforreleasecompletion: true
                    owners: 'mmainer@microsoft.com,gavinbarron@microsoft.com'
                    approvers: 'mmainer@microsoft.com,christiano@microsoft.com,gavinbarron@microsoft.com,lramosvea@microsoft.com'
                    serviceendpointurl: 'https://api.esrp.microsoft.com'
                    mainpublisher: 'ESRPRELPACMAN'
                    domaintenantid: 'cdc5aeea-15c5-4db6-b079-fcadd2505dc2'